### ISSUE TITLE
Firmware version

### ISSUE THREAD

**Issue by mjharden** [HewlettPackard/oneview-osdeployment#4]
When I install the 3.10 modules, I am able to connect to the server, however when I run the Mount-Virtualmedia.ps1 powershell script, it indicates:

Disable-HPRESTCertificateAuthentication : The term 
'Disable-HPRESTCertificateAuthentication' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At C:\Users\blah\Documents\WindowsPowerShell\Modules\Mount-VirtualMedia.ps1:236 
char:5
+     Disable-HPRESTCertificateAuthentication
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Disable-HPRESTCertificateAuthenticatio 
   n:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Also, will this work with an ISO from FTP, or can this work with a Local Virtual Media(CD/DVD)?

Thanks!

**Comment by ChrisLynchHPE** [comment]
Holy moly.  Sincere apologies for getting to this so late (well over a year).  This is caused by the fact you need the HPiLOCmdlets installed, which is a prerequisite.  If you don't, then you get this error.

This script will only work with the ISO hosted on an HTTP or FTP location, not your local PC as this uses scripted virtual media commands.  Which means you need to have an iLO Advanced license.
